import type { Metadata } from "next";
import "./globals.css";
import { fira_sans } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Monte Yoon Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fira_sans.className} antialiased`}>{children}</body>
    </html>
  );
}
